@startmindmap
*:XAI & Ontology 
  Applications
;
**:Privacy 
;
***:Higher abstraction level.
;
/'
Knowledge graph-based rich and confidentiality preserving 
Explainable Artificial Intelligence (XAI) 
'/
**:Generate data based on relations
;
**:Auxiliate in generating training data for a 
mimic model that is inherently understandable.;
/'
Doctor XAI: an ontology-based approach to black-box 
sequential data classification explanations
'/
**:Ontology framework
;
***:Compare and evaluate different explanations
;
/'
Quantitative and Ontology-Based Comparison of 
Explanations for Image Classification
'/
***:Cognitive and Perceptualy addressable
;
/'
Using Perceptual and Cognitive Explanations for 
Enhanced Human-Agent Team Performance
'/
***:Relations between AI, use cases and explanations.
;
/'
Towards FAIR Explainable AI: a standardized ontology for 
mapping XAI solutions to use cases, explanations, and AI 
systems
'/
***:Help Collect feedback, explanations, recommended 
options and user action
;
/'
XAI-KG: Knowledge Graph to Support XAI and Decision-Making 
in Manufacturing
'/

***:Provide Accountability
;
****:Manufacturing
;
/'
An Ontology-based approach for making
Machine Learning systems Accountable
'/
**:Provide explanation 
;
***:Chatbot freespeech
;
/'
THE DESIGN AND IMPLEMENTATION OF LANGUAGE LEARNING 
CHATBOT WITH XAI USING ONTOLOGY AND TRANSFER LEARNING
'/
**:Class Hierarchy
;
***:Provide induction with heuristic algorithm
;
/'
Towards Human-Compatible XAI: Explaining Data Differentials
 with Concept Induction over Background Knowledge
'/
@endmindmap